package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Engine_Package_BuildPackage'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Engine_Package_BuildPackage")) {
    params {
        expect {
            select("XenkoPlatforms", "Windows;Android;UWP;iOS;Linux;macOS", label = "Platforms",
                    allowMultiple = true, valueSeparator = ";",
                    options = listOf("Windows", "UWP", "iOS", "Android", "Linux", "macOS"))
        }
        update {
            select("XenkoPlatforms", "Windows", label = "Platforms",
                    allowMultiple = true, valueSeparator = ";",
                    options = listOf("Windows", "UWP", "iOS", "Android", "Linux", "macOS"))
        }
        add {
            param("XenkoBuildPrerequisitesInstaller", "false")
        }
    }
}
