package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'Xenko'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("Xenko")) {
    val expected = GitVcsRoot({
        id("Xenko")
        name = "xenko"
        url = "git@github.com:xenko3d/xenko.git"
        branchSpec = """
            +:refs/heads/*
            +:refs/(pull/*/merge)
        """.trimIndent()
        agentCleanPolicy = GitVcsRoot.AgentCleanPolicy.ALWAYS
        authMethod = uploadedKey {
            uploadedKey = "GitHub"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        name = "vvvv-stride"
        url = "git@github.com:vvvv/stride.git"
        authMethod = uploadedKey {
            userName = ""
            uploadedKey = "teamcity_priv.ppk"
            passphrase = "zxxc1e9a1d9209ccaa0"
        }
    }

}
